import os
import re

courses = {
    "constitutional-law": [
        "Strict Scrutiny",
        "Intermediate Scrutiny",
        "Rational Basis Review",
        "Rational Basis With Bite",
        "Dormant Commerce Clause",
        "Commerce Clause",
        "Necessary and Proper Clause",
        "Supremacy Clause",
        "Preemption",
        "Express Preemption",
        "Implied Preemption",
        "Field Preemption",
        "Conflict Preemption",
        "Anti-Commandeering Doctrine",
        "Nondelegation Doctrine",
        "Major Questions Doctrine",
        "Standing",
        "Ripeness",
        "Mootness",
        "Political Question Doctrine",
        "State Action Doctrine",
        "Incorporation Doctrine",
        "Substantive Due Process",
        "Procedural Due Process",
        "Equal Protection",
        "Facial Challenge",
        "As-Applied Challenge",
        "Overbreadth Doctrine",
        "Vagueness Doctrine",
        "Content-Based Restriction",
        "Content-Neutral Restriction",
        "Time Place and Manner Restrictions",
        "Prior Restraint",
        "Symbolic Speech",
        "Commercial Speech Doctrine",
        "Incitement Test",
        "True Threats Doctrine",
        "Fighting Words Doctrine",
        "Obscenity Test",
        "Establishment Clause",
        "Free Exercise Clause",
        "Free Speech Clause",
        "Free Press Clause",
        "Freedom of Association",
        "Petition Clause",
        "Compelled Speech Doctrine",
        "Public Forum Doctrine",
        "Limited Public Forum",
        "Nonpublic Forum",
        "Viewpoint Discrimination",
        "Content Discrimination",
        "State Sovereign Immunity",
        "Eleventh Amendment Immunity",
        "Qualified Immunity",
        "Absolute Immunity",
        "Executive Privilege",
        "Legislative Veto",
        "Appointments Clause",
        "Removal Power",
        "Take Care Clause",
        "Executive Power Theory",
        "War Powers",
        "Spending Power",
        "Taxing Power",
        "Treaty Power",
        "Privileges or Immunities Clause",
        "Privileges and Immunities Clause",
        "Takings Clause",
        "Public Use Requirement",
        "Regulatory Taking",
        "Exactions Doctrine",
        "Excessive Fines Clause",
        "Cruel and Unusual Punishment",
        "Double Jeopardy",
        "Self-Incrimination Clause",
        "Ex Post Facto Clause",
        "Bill of Attainder",
        "Guarantee Clause",
        "One Person One Vote",
        "Independent and Adequate State Grounds",
        "Judicial Review",
        "Severability",
        "Narrow Tailoring",
        "Least Restrictive Means",
        "Undue Burden Test"
    ],

    "civil-procedure": [
        "Subject Matter Jurisdiction",
        "Federal Question Jurisdiction",
        "Diversity Jurisdiction",
        "Complete Diversity",
        "Amount in Controversy",
        "Supplemental Jurisdiction",
        "Removal Jurisdiction",
        "Remand",
        "Personal Jurisdiction",
        "General Jurisdiction",
        "Specific Jurisdiction",
        "Tag Jurisdiction",
        "Consent to Jurisdiction",
        "Minimum Contacts",
        "Purposeful Availment",
        "Purposeful Direction",
        "Relatedness Requirement",
        "Fair Play and Substantial Justice",
        "Long Arm Statute",
        "Notice Pleading",
        "Plausibility Pleading",
        "Rule 12(b)(6) Motion",
        "Rule 12(b)(1) Motion",
        "Rule 12(b)(2) Motion",
        "Rule 12(b)(3) Motion",
        "Rule 12(b)(5) Motion",
        "Service of Process",
        "Waiver of Service",
        "Venue",
        "Transfer of Venue",
        "Forum Non Conveniens",
        "Erie Doctrine",
        "Outcome Determinative Test",
        "Byrd Balancing",
        "Hanna Analysis",
        "Rules Enabling Act",
        "Choice of Law in Federal Court",
        "Pleading in the Alternative",
        "Amended Pleadings",
        "Relation Back Doctrine",
        "Compulsory Counterclaim",
        "Permissive Counterclaim",
        "Crossclaim",
        "Joinder of Claims",
        "Permissive Joinder of Parties",
        "Compulsory Joinder",
        "Necessary Party",
        "Indispensable Party",
        "Intervention of Right",
        "Permissive Intervention",
        "Interpleader",
        "Class Action",
        "Class Certification",
        "Numerosity",
        "Commonality",
        "Typicality",
        "Adequacy of Representation",
        "Predominance",
        "Superiority",
        "Discovery Scope",
        "Work Product Doctrine",
        "Attorney Client Privilege",
        "Protective Order",
        "Summary Judgment",
        "Judgment as a Matter of Law",
        "Renewed Judgment as a Matter of Law",
        "New Trial Motion",
        "Default Judgment",
        "Claim Preclusion",
        "Issue Preclusion",
        "Res Judicata",
        "Collateral Estoppel",
        "Full Faith and Credit",
        "Final Judgment Rule",
        "Interlocutory Appeal",
        "Collateral Order Doctrine",
        "Mandamus",
        "Harmless Error",
        "Standard of Review",
        "Abuse of Discretion",
        "De Novo Review",
        "Clearly Erroneous Standard"
    ],

    "contracts": [
        "Offer",
        "Acceptance",
        "Consideration",
        "Bargained For Exchange",
        "Promissory Estoppel",
        "Reliance",
        "Restitution",
        "Unjust Enrichment",
        "Objective Theory of Assent",
        "Mutual Assent",
        "Mailbox Rule",
        "Mirror Image Rule",
        "Battle of the Forms",
        "Firm Offer Rule",
        "Option Contract",
        "Unilateral Contract",
        "Bilateral Contract",
        "Requirements Contract",
        "Output Contract",
        "Good Faith Performance",
        "Implied Duty of Good Faith",
        "Illusory Promise",
        "Past Consideration",
        "Preexisting Duty Rule",
        "Contract Modification",
        "Accord and Satisfaction",
        "Novation",
        "Delegation",
        "Assignment",
        "Third Party Beneficiary",
        "Intended Beneficiary",
        "Incidental Beneficiary",
        "Condition Precedent",
        "Condition Subsequent",
        "Constructive Condition",
        "Substantial Performance",
        "Material Breach",
        "Minor Breach",
        "Perfect Tender Rule",
        "Installment Contract",
        "Anticipatory Repudiation",
        "Adequate Assurances",
        "Impossibility",
        "Impracticability",
        "Frustration of Purpose",
        "Mutual Mistake",
        "Unilateral Mistake",
        "Misrepresentation",
        "Fraud in the Inducement",
        "Duress",
        "Undue Influence",
        "Unconscionability",
        "Procedural Unconscionability",
        "Substantive Unconscionability",
        "Parol Evidence Rule",
        "Integration Clause",
        "Statute of Frauds",
        "Main Purpose Rule",
        "Part Performance",
        "Expectation Damages",
        "Consequential Damages",
        "Incidental Damages",
        "Liquidated Damages",
        "Penalty Clause",
        "Duty to Mitigate",
        "Specific Performance",
        "Reformation",
        "Rescission",
        "Cover",
        "Entrustment Rule",
        "Risk of Loss",
        "Express Warranty",
        "Implied Warranty of Merchantability",
        "Implied Warranty of Fitness",
        "Revocation of Acceptance",
        "Cure",
        "Identification to the Contract"
    ],

    "torts": [
        "Negligence",
        "Duty",
        "Breach",
        "Actual Cause",
        "Proximate Cause",
        "But For Causation",
        "Substantial Factor Test",
        "Foreseeability",
        "Res Ipsa Loquitur",
        "Negligence Per Se",
        "Reasonable Person Standard",
        "Professional Standard of Care",
        "Medical Malpractice",
        "Informed Consent",
        "Strict Liability",
        "Products Liability",
        "Manufacturing Defect",
        "Design Defect",
        "Failure to Warn",
        "Consumer Expectation Test",
        "Risk Utility Test",
        "Assumption of Risk",
        "Comparative Negligence",
        "Contributory Negligence",
        "Last Clear Chance",
        "Joint and Several Liability",
        "Alternative Liability",
        "Market Share Liability",
        "Vicarious Liability",
        "Respondeat Superior",
        "Scope of Employment",
        "Independent Contractor Rule",
        "Negligent Hiring",
        "Negligent Entrustment",
        "Attractive Nuisance Doctrine",
        "Premises Liability",
        "Open and Obvious Danger",
        "Trespass to Land",
        "Trespass to Chattels",
        "Conversion",
        "Private Necessity",
        "Public Necessity",
        "Battery",
        "Assault",
        "False Imprisonment",
        "Intentional Infliction of Emotional Distress",
        "Transferred Intent",
        "Defamation",
        "Libel",
        "Slander",
        "Slander Per Se",
        "Actual Malice",
        "Public Figure Doctrine",
        "Intrusion Upon Seclusion",
        "Public Disclosure of Private Facts",
        "False Light",
        "Appropriation",
        "Nuisance",
        "Private Nuisance",
        "Public Nuisance",
        "Abnormally Dangerous Activity",
        "Wrongful Death",
        "Survival Action",
        "Eggshell Skull Rule",
        "Avoidable Consequences Doctrine"
    ],

    "criminal-law": [
        "Actus Reus",
        "Mens Rea",
        "Specific Intent",
        "General Intent",
        "Malice",
        "Strict Liability",
        "Transferred Intent",
        "Concurrence",
        "Causation in Criminal Law",
        "But For Cause",
        "Proximate Cause in Criminal Law",
        "Homicide",
        "Murder",
        "Malice Aforethought",
        "Felony Murder Rule",
        "Manslaughter",
        "Voluntary Manslaughter",
        "Involuntary Manslaughter",
        "Heat of Passion",
        "Adequate Provocation",
        "Depraved Heart Murder",
        "Attempt",
        "Solicitation",
        "Conspiracy",
        "Pinkerton Liability",
        "Accomplice Liability",
        "Principal in the First Degree",
        "Accessory Before the Fact",
        "Accessory After the Fact",
        "Withdrawal from Conspiracy",
        "Wharton Rule",
        "Merger Doctrine",
        "Burglary",
        "Arson",
        "Robbery",
        "Larceny",
        "Embezzlement",
        "False Pretenses",
        "Receiving Stolen Property",
        "Forgery",
        "Uttering",
        "Battery in Criminal Law",
        "Assault in Criminal Law",
        "Kidnapping",
        "Rape",
        "Statutory Rape",
        "Insanity Defense",
        "MNaghten Rule",
        "Irresistible Impulse Test",
        "Durham Test",
        "Model Penal Code Insanity Test",
        "Intoxication Defense",
        "Voluntary Intoxication",
        "Involuntary Intoxication",
        "Self Defense",
        "Defense of Others",
        "Defense of Property",
        "Necessity Defense",
        "Duress Defense",
        "Mistake of Fact",
        "Mistake of Law",
        "Entrapment",
        "Impossibility Defense",
        "Abandonment Defense"
    ],

    "property": [
        "Fee Simple Absolute",
        "Fee Simple Determinable",
        "Fee Simple Subject to Condition Subsequent",
        "Fee Simple Subject to Executory Limitation",
        "Life Estate",
        "Reversion",
        "Possibility of Reverter",
        "Right of Entry",
        "Remainder",
        "Vested Remainder",
        "Contingent Remainder",
        "Executory Interest",
        "Rule Against Perpetuities",
        "Class Gifts",
        "Joint Tenancy",
        "Tenancy in Common",
        "Tenancy by the Entirety",
        "Severance of Joint Tenancy",
        "Partition",
        "Ouster",
        "Adverse Possession",
        "Color of Title",
        "Tacking",
        "Disability Tolling",
        "Discovery Rule",
        "Replevin",
        "Bailment",
        "Gift Inter Vivos",
        "Gift Causa Mortis",
        "Delivery Requirement",
        "Constructive Delivery",
        "Accessions",
        "Fixtures",
        "Waste",
        "Voluntary Waste",
        "Permissive Waste",
        "Ameliorative Waste",
        "Landlord Tenant Law",
        "Tenancy for Years",
        "Periodic Tenancy",
        "Tenancy at Will",
        "Tenancy at Sufferance",
        "Constructive Eviction",
        "Implied Warranty of Habitability",
        "Covenant of Quiet Enjoyment",
        "Assignment of Lease",
        "Sublease",
        "Privity of Estate",
        "Privity of Contract",
        "Surrender",
        "Mitigation in Lease Cases",
        "Easement",
        "Easement Appurtenant",
        "Easement in Gross",
        "Implied Easement",
        "Easement by Necessity",
        "Prescription",
        "License",
        "Covenant Running With the Land",
        "Equitable Servitude",
        "Real Covenant",
        "Notice Recording Statute",
        "Race Recording Statute",
        "Race Notice Statute",
        "Bona Fide Purchaser",
        "Shelter Rule",
        "Inquiry Notice",
        "Mortgage",
        "Title Theory",
        "Lien Theory",
        "Equitable Mortgage",
        "Foreclosure",
        "Redemption",
        "Installment Land Contract",
        "Zoning",
        "Nuisance in Property Law"
    ],

    "evidence": [
        "Relevance",
        "Probative Value",
        "Unfair Prejudice",
        "Rule 403 Balancing",
        "Character Evidence",
        "Propensity Evidence",
        "MIMIC Evidence",
        "Habit Evidence",
        "Subsequent Remedial Measures",
        "Settlement Offers",
        "Offers to Pay Medical Expenses",
        "Plea Discussions",
        "Liability Insurance",
        "Authentication",
        "Best Evidence Rule",
        "Original Writing Rule",
        "Duplicate Admissibility",
        "Hearsay",
        "Nonhearsay Purpose",
        "Verbal Acts",
        "Statement of Party Opponent",
        "Adoptive Admission",
        "Prior Inconsistent Statement",
        "Prior Consistent Statement",
        "Prior Identification",
        "Present Sense Impression",
        "Excited Utterance",
        "Then Existing Mental State",
        "Statement for Medical Diagnosis",
        "Recorded Recollection",
        "Business Records Exception",
        "Public Records Exception",
        "Learned Treatise Exception",
        "Ancient Documents Exception",
        "Statement Against Interest",
        "Dying Declaration",
        "Former Testimony",
        "Forfeiture by Wrongdoing",
        "Residual Exception",
        "Declarant Unavailability",
        "Confrontation Clause",
        "Testimonial Statement",
        "Impeachment",
        "Bias Impeachment",
        "Prior Conviction Impeachment",
        "Specific Instances on Cross",
        "Refreshing Recollection",
        "Expert Testimony",
        "Daubert Standard",
        "Frye Standard",
        "Lay Opinion",
        "Judicial Notice",
        "Dead Man Statute",
        "Privilege",
        "Attorney Client Privilege",
        "Spousal Immunity",
        "Marital Communications Privilege",
        "Physician Patient Privilege",
        "Psychotherapist Patient Privilege",
        "Work Product Doctrine",
        "Rape Shield Rule"
    ],

    "corporations": [
        "Business Judgment Rule",
        "Duty of Care",
        "Duty of Loyalty",
        "Duty of Good Faith",
        "Entire Fairness Review",
        "Waste Doctrine",
        "Corporate Opportunity Doctrine",
        "Interested Director Transaction",
        "Piercing the Corporate Veil",
        "Alter Ego Doctrine",
        "De Facto Corporation",
        "Corporation by Estoppel",
        "Promoter Liability",
        "Preincorporation Contract",
        "Ultra Vires",
        "Derivative Suit",
        "Demand Requirement",
        "Demand Futility",
        "Special Litigation Committee",
        "Direct Versus Derivative Claim",
        "Closely Held Corporation",
        "Oppression of Minority Shareholders",
        "Appraisal Rights",
        "Shareholder Voting",
        "Cumulative Voting",
        "Proxy Voting",
        "Proxy Contest",
        "Quorum Requirement",
        "Inspection Rights",
        "Dividend Distributions",
        "Solvency Test",
        "Authorized Shares",
        "Issued Shares",
        "Outstanding Shares",
        "Par Value",
        "Preferred Stock",
        "Preemptive Rights",
        "Subscription Agreement",
        "Board of Directors",
        "Officer Authority",
        "Actual Authority",
        "Apparent Authority",
        "Indemnification of Directors",
        "Exculpation Clause",
        "Merger",
        "De Facto Merger Doctrine",
        "Tender Offer",
        "Freeze Out Merger",
        "Parent Subsidiary Merger",
        "Successor Liability",
        "Benefit Corporation"
    ],

    "administrative-law": [
        "Chevron Deference",
        "Skidmore Deference",
        "Auer Deference",
        "Seminole Rock Deference",
        "Major Questions Doctrine",
        "Nondelegation Doctrine",
        "Intelligible Principle Test",
        "Arbitrary and Capricious Review",
        "Substantial Evidence Review",
        "Formal Rulemaking",
        "Informal Rulemaking",
        "Notice and Comment Rulemaking",
        "Formal Adjudication",
        "Informal Adjudication",
        "Agency Action",
        "Final Agency Action",
        "Exhaustion of Administrative Remedies",
        "Ripeness in Administrative Law",
        "Standing in Administrative Law",
        "Judicial Review of Agency Action",
        "Reviewability Presumption",
        "Committed to Agency Discretion",
        "Interpretive Rule",
        "Legislative Rule",
        "Policy Statement",
        "Guidance Document",
        "Retroactivity in Administrative Law",
        "Chenery Doctrine",
        "Accardi Doctrine",
        "Administrative Record Rule",
        "Hard Look Review",
        "Organic Statute",
        "Delegated Authority",
        "APA Section 553",
        "APA Section 706",
        "Due Process in Agency Proceedings"
    ],

    "federal-courts": [
        "Article III Jurisdiction",
        "Case or Controversy Requirement",
        "Standing in Federal Courts",
        "Injury in Fact",
        "Causation for Standing",
        "Redressability",
        "Prudential Standing",
        "Third Party Standing",
        "Zone of Interests Test",
        "Ripeness in Federal Courts",
        "Mootness in Federal Courts",
        "Political Question Doctrine",
        "Advisory Opinion Doctrine",
        "Independent and Adequate State Grounds",
        "Supreme Court Review of State Judgments",
        "Adequate and Independent State Ground Doctrine",
        "Rooker Feldman Doctrine",
        "Younger Abstention",
        "Pullman Abstention",
        "Burford Abstention",
        "Colorado River Abstention",
        "Anti Injunction Act",
        "Eleventh Amendment",
        "Ex Parte Young Doctrine",
        "State Sovereign Immunity",
        "Qualified Immunity",
        "Absolute Judicial Immunity",
        "Prosecutorial Immunity",
        "Bivens Action",
        "Section 1983",
        "Habeas Corpus",
        "Suspension Clause",
        "Exhaustion in Habeas",
        "Procedural Default",
        "AEDPA Deference",
        "Independent and Adequate State Ground in Habeas",
        "Cause and Prejudice",
        "Actual Innocence Gateway",
        "Younger Noninterference Principle",
        "Domestic Relations Exception",
        "Probate Exception",
        "Protective Jurisdiction",
        "Congressional Control of Jurisdiction",
        "Exceptions Clause",
        "Osborn Protective Jurisdiction Theory"
    ],

    "secured-transactions": [
        "Security Interest",
        "Attachment",
        "Perfection",
        "Financing Statement",
        "Purchase Money Security Interest",
        "PMSI Superpriority",
        "After Acquired Property Clause",
        "Proceeds",
        "Future Advances Clause",
        "Default",
        "Repossession",
        "Breach of the Peace",
        "Strict Foreclosure",
        "Disposition of Collateral",
        "Commercial Reasonableness",
        "Surplus and Deficiency",
        "Priority Rule",
        "Buyer in Ordinary Course",
        "Lien Creditor",
        "Fixture Filing",
        "Accessions in Secured Transactions",
        "Commingled Goods",
        "Control for Deposit Accounts",
        "Automatic Perfection",
        "Authentication Requirement"
    ],

    "conflict-of-laws": [
        "Traditional Choice of Law",
        "Vested Rights Theory",
        "Most Significant Relationship Test",
        "Governmental Interest Analysis",
        "False Conflict",
        "True Conflict",
        "Dépeçage",
        "Renvoi",
        "Substance Procedure Distinction",
        "Borrowing Statute",
        "Public Policy Exception",
        "Lex Loci Delicti",
        "Lex Loci Contractus",
        "Party Autonomy in Choice of Law",
        "Forum Selection Clause",
        "Full Faith and Credit in Conflicts",
        "Recognition of Foreign Judgments",
        "Enforcement of Sister State Judgments",
        "Domicile",
        "Residence in Conflicts"
    ],

    "tax-law": [
        "Gross Income",
        "Realization Requirement",
        "Recognition Requirement",
        "Adjusted Gross Income",
        "Taxable Income",
        "Capital Asset",
        "Capital Gain",
        "Capital Loss",
        "Basis",
        "Adjusted Basis",
        "Amount Realized",
        "Like Kind Exchange",
        "Assignment of Income Doctrine",
        "Constructive Receipt",
        "Claim of Right Doctrine",
        "Tax Benefit Rule",
        "Business Expense Deduction",
        "Ordinary and Necessary Expense",
        "Depreciation",
        "Amortization",
        "Dividend Taxation",
        "Corporate Double Taxation",
        "Partnership Pass Through Taxation",
        "S Corporation Election",
        "Substance Over Form",
        "Step Transaction Doctrine",
        "Economic Substance Doctrine",
        "Wash Sale Rule",
        "Gift Tax",
        "Estate Tax"
    ],

    "intellectual-property": [
        "Copyright",
        "Fixation Requirement",
        "Originality Requirement",
        "Idea Expression Dichotomy",
        "Merger Doctrine in Copyright",
        "Scenes A Faire",
        "Fair Use",
        "Transformative Use",
        "Work Made for Hire",
        "Joint Authorship",
        "Derivative Work",
        "Trademark",
        "Distinctiveness Spectrum",
        "Generic Mark",
        "Descriptive Mark",
        "Suggestive Mark",
        "Arbitrary Mark",
        "Fanciful Mark",
        "Secondary Meaning",
        "Likelihood of Confusion",
        "Dilution",
        "Trade Dress",
        "Patent",
        "Novelty",
        "Nonobviousness",
        "Utility",
        "Enablement",
        "Written Description",
        "Doctrine of Equivalents",
        "Prosecution History Estoppel",
        "Trade Secret",
        "Misappropriation of Trade Secrets",
        "Inevitable Disclosure Doctrine",
        "Right of Publicity"
    ],

    "professional-responsibility": [
        "Attorney Client Privilege",
        "Confidentiality of Information",
        "Conflict of Interest",
        "Concurrent Conflict",
        "Successive Conflict",
        "Imputed Disqualification",
        "Informed Consent",
        "Competence",
        "Diligence",
        "Communication Duty",
        "Safekeeping Property",
        "Business Transactions With Clients",
        "Attorney Fees Reasonableness",
        "Contingent Fee Rule",
        "Candor to the Tribunal",
        "Duty of Fairness to Opposing Party",
        "Truthfulness in Statements to Others",
        "No Contact Rule",
        "Unauthorized Practice of Law",
        "Multijurisdictional Practice",
        "Prosecutor Special Responsibilities",
        "Duty to Report Misconduct",
        "Supervisory Responsibility",
        "Subordinate Lawyer Responsibilities",
        "Advertising Rules",
        "Solicitation Rules",
        "Trial Publicity",
        "Withdrawal From Representation",
        "Mandatory Withdrawal",
        "Permissive Withdrawal",
        "Organization as Client",
        "Reporting Up",
        "Reporting Out",
        "Prospective Client Duties",
        "Duty of Loyalty",
        "Duty of Confidentiality in PR"
    ]
}

os.makedirs("doctrine", exist_ok=True)

def slugify(text):
    return re.sub(r'[^a-z0-9]+', '-', text.lower()).strip('-')

for course, terms in courses.items():
    os.makedirs(course, exist_ok=True)

all_course_links = []

for course, terms in courses.items():
    course_title = course.replace("-", " ").title()
    term_links = []

    for i, term in enumerate(terms):
        slug = slugify(term)
        filename = f"doctrine/{slug}.html"

        related_terms = [t for t in terms if t != term][:8]
        related_links = "\n".join(
            [f'<li><a href="/doctrine/{slugify(t)}.html">{t}</a></li>' for t in related_terms]
        )

        doctrine_html = f"""<!DOCTYPE html>
<html>
<head>
  <title>What Is {term}? | JurisTerms</title>
  <meta name="description" content="Plain English explanation of {term} for law students, bar exam takers, and legal readers.">
  <link rel="stylesheet" href="../style.css">
</head>
<body>
  <h1>{term}</h1>

  <p><strong>Course:</strong> <a href="/{course}/index.html">{course_title}</a></p>

  <p>{term} is a legal doctrine or concept commonly studied in {course_title} and tested in law school courses, bar exam preparation, and legal analysis.</p>

  <p>In plain English, {term} refers to a rule, principle, test, or framework that courts use when deciding certain legal questions. Understanding the meaning of {term} helps students recognize how lawyers and judges organize legal arguments.</p>

  <p>The doctrine matters because it gives courts a predictable way to evaluate disputes. When a legal issue falls within the scope of {term}, the doctrine can shape how a court interprets facts, applies precedent, and reaches a conclusion.</p>

  <p>Law students often encounter {term} in casebooks, outlines, class discussions, and exam hypos. A strong working understanding of {term} makes it easier to identify issues, articulate rules, and apply doctrine in a structured way.</p>

  <h2>Related {course_title} Terms</h2>
  <ul>
  {related_links}
  </ul>

  <p><a href="/{course}/index.html">Back to {course_title}</a></p>
  <p><a href="/">Back to JurisTerms Home</a></p>
</body>
</html>
"""
        with open(filename, "w") as f:
            f.write(doctrine_html)

        term_links.append(f'<li><a href="/doctrine/{slug}.html">{term}</a></li>')

    course_html = f"""<!DOCTYPE html>
<html>
<head>
  <title>{course_title} Terms | JurisTerms</title>
  <meta name="description" content="Key legal doctrines and terms in {course_title}, explained in plain English.">
  <link rel="stylesheet" href="../style.css">
</head>
<body>
  <h1>{course_title}</h1>
  <p>Browse key legal doctrines and concepts commonly studied in {course_title}.</p>
  <ul>
    {' '.join(term_links)}
  </ul>
  <p><a href="/">Back to JurisTerms Home</a></p>
</body>
</html>
"""
    with open(f"{course}/index.html", "w") as f:
        f.write(course_html)

print("Site generated successfully.")
